#!/bin/bash

################################################################################

# Allow current host user to access files generated by Docker 'root' user.
chown -R ${HOST_UID}:${HOST_GID} /home/${HOST_USER}/ur-o2as/
chown -R ${HOST_UID}:${HOST_GID} /root/share/
chown -R ${HOST_UID}:${HOST_GID} /root/.ros/
