<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"
       name="o2as_base_scene" >

  <!-- This is the main file defining our robot arrangement and physical environment. -->

  <!-- Calibration from 20 August 2018 -->
  <!-- Calibration help: If the robot is not moving far enough to the calibration point, increase these distances -->
  <xacro:property name="a_bot_x" value="-0.005"/>
  <xacro:property name="a_bot_y" value="-0.543"/>
  <xacro:property name="b_bot_x" value="0.001"/>
  <xacro:property name="b_bot_y" value="0.529"/>
  <xacro:property name="c_bot_x" value="-0.5"/>
  <xacro:property name="c_bot_y" value="0.0"/>

  <xacro:property name="bots_z" value="0.75"/>

  <!-- common stuff -->
  <xacro:include filename="$(find ur_description)/urdf/common.gazebo.xacro" />
  <xacro:include filename="$(find o2as_gazebo)/urdf/o2as_base_scene.gazebo" />
  <xacro:include filename="$(find realsense2_camera)/urdf/_d435.urdf.xacro" />

  <!-- robots -->
  <!-- <xacro:include filename="$(find o2as_scene_description)/urdf/ur10.urdf.xacro" /> -->
  <xacro:include filename="$(find o2as_scene_description)/urdf/ur5.urdf.xacro" />
  <xacro:include filename="$(find o2as_scene_description)/urdf/ur3.urdf.xacro" />

  <!-- Scene items (trays, bins...) -->
  <!-- <xacro:include filename="$(find o2as_scene_description)/urdf/taskboard_scene.xacro" /> -->
  <xacro:include filename="$(find o2as_scene_description)/urdf/kitting_scene_osaka.xacro" />
  <!-- <xacro:include filename="$(find o2as_scene_description)/urdf/assembly_scene.xacro" /> -->
  
  <!-- Robot bases -->
  <!-- Putting these at height 0.0 makes them intersect with the ground, so they are elevated. -->
  <!-- There are some instabilities when the box is big, for some reason. -->
  <xacro:include filename="$(find o2as_scene_description)/urdf/o2as_osakabase.xacro" />
  <xacro:o2as_base boxname="a_bot_base_smfl" parent="o2as_ground">
    <origin xyz="${a_bot_x-.4/2} ${a_bot_y-.4/2} ${bots_z-.06}" rpy="0 0 0" />   
  </xacro:o2as_base>
  <xacro:o2as_base boxname="b_bot_base_smfl" parent="o2as_ground">
    <origin xyz="${b_bot_x-.4/2} ${b_bot_y-.4/2} ${bots_z-.06}" rpy="0 0 0" />   
  </xacro:o2as_base>
  <xacro:o2as_base boxname="c_bot_base_smfl" parent="o2as_ground">
    <origin xyz="${c_bot_x-.4/2-.16} ${c_bot_y-.4/2-.1} ${bots_z-.06}" rpy="0 0 0" />   
  </xacro:o2as_base>

  <!-- Main workspace -->
  <!-- The surface is 0.01 m below the robot bases and the "workspace_center" frame. -->
  <xacro:include filename="$(find o2as_scene_description)/urdf/o2as_box.xacro" />
  <xacro:property name="plate_w" value="0.9"/>
  <xacro:property name="plate_l" value="0.75"/>
  <xacro:o2as_box boxname="workbox" box_w="${plate_w}" box_l="${plate_l}" box_h=".01" parent="o2as_ground">
    <origin xyz="${-plate_w/2+.1} ${-plate_l/2} ${bots_z-0.196}" rpy="0 0 0" />   
  </xacro:o2as_box>

  <link name="workspace_center" />
  <joint name="world_to_workspace" type="fixed">
    <parent link="o2as_ground" />
    <child link="workspace_center" />
    <origin xyz="0.0 0.0 ${bots_z+.01-0.196}" rpy="0.0 0.0 0.0" />
  </joint>

  <!-- Screw holder & screw tool visual -->
  <!-- <xacro:include filename="$(find o2as_scene_description)/urdf/screw_tools.xacro" /> -->

  <!-- Feeders -->
  <!-- <xacro:include filename="$(find o2as_scene_description)/urdf/screw_feeder.xacro" />
  <xacro:screw_feeder feedername="m3_feeder" parent="a_bot_base_smfl">
    <origin xyz=".1 .4 .05" rpy="0 0 ${pi/2}" />   
  </xacro:screw_feeder>
  <xacro:screw_feeder feedername="m4_feeder" parent="c_bot_base_smfl">
    <origin xyz=".45 .05 .05" rpy="0 0 0" />   
  </xacro:screw_feeder> -->
  <!-- <xacro:screw_feeder feedername="m5_feeder" parent="c_bot_base_smfl">
    <origin xyz=".45 .2 .05" rpy="0 0 0" />   
  </xacro:screw_feeder> -->

  <!-- robot arms -->    
  <xacro:ur5_robot prefix="a_bot_" joint_limited="true"
    shoulder_pan_lower_limit="0.0" shoulder_pan_upper_limit="${pi}"
    shoulder_lift_lower_limit="${-pi}" shoulder_lift_upper_limit="0.0"
    elbow_joint_lower_limit="0.0" elbow_joint_upper_limit="${pi}"
    wrist_1_lower_limit="${-pi}" wrist_1_upper_limit="0.3"
    wrist_2_lower_limit="${-pi}" wrist_2_upper_limit="${pi}"
    wrist_3_lower_limit="${-pi}" wrist_3_upper_limit="${pi}"/>
   
  <xacro:ur5_robot prefix="b_bot_" joint_limited="true"
    shoulder_pan_lower_limit="${-pi}" shoulder_pan_upper_limit="${pi}"
    shoulder_lift_lower_limit="${-pi}" shoulder_lift_upper_limit="0.0"
    elbow_joint_lower_limit="0.0" elbow_joint_upper_limit="${pi}"
    wrist_1_lower_limit="${-pi}" wrist_1_upper_limit="0.3"
    wrist_2_lower_limit="${-pi}" wrist_2_upper_limit="${pi}"
    wrist_3_lower_limit="${-pi}" wrist_3_upper_limit="${pi}"/>
  
  <xacro:ur3_robot prefix="c_bot_" joint_limited="true"
    shoulder_pan_lower_limit="0.0" shoulder_pan_upper_limit="${pi}"
    shoulder_lift_lower_limit="${-pi}" shoulder_lift_upper_limit="0.0"
    elbow_joint_lower_limit="0.0" elbow_joint_upper_limit="${pi}"
    wrist_1_lower_limit="${-pi}" wrist_1_upper_limit="${pi}"
    wrist_2_lower_limit="${-pi}" wrist_2_upper_limit="${pi}"
    wrist_3_lower_limit="${-pi}" wrist_3_upper_limit="${pi}"/>

  <link name="o2as_ground" />

  <joint name="world_a_bot_joint" type="fixed">
    <parent link="o2as_ground" />
    <child link="a_bot_base_link" />
    <origin xyz="${a_bot_x} ${a_bot_y} ${bots_z}" rpy="0.0 0.0 0.0" />
  </joint>

  <joint name="world_b_bot_joint" type="fixed">
    <parent link="o2as_ground" />
    <child link = "b_bot_base_link" />
    <origin xyz="${b_bot_x} ${b_bot_y} ${bots_z}" rpy="0.0 0.0 ${-pi}" />
  </joint>

  <joint name="world_c_bot_joint" type="fixed">
    <parent link="o2as_ground" />
    <child link = "c_bot_base_link" />
    <origin xyz="${c_bot_x} ${c_bot_y} ${bots_z}" rpy="0.0 0.0 ${-pi/2}" />
  </joint>

  <!-- spawn and attach grippers -->
  <!-- <xacro:include filename="$(find o2as_scene_description)/urdf/precision_gripper.xacro" />
  <xacro:precision_gripper prefix="a_bot_"  grippername = "gripper" parent = "a_bot_tool0">
    <origin xyz="0.0 0 0.04" rpy="0 ${pi/2} 0"/>
  </xacro:precision_gripper> -->

  <xacro:include filename="$(find o2as_scene_description)/urdf/InnerOnlyGripper.xacro" />
  <xacro:InnerOnlyGripper prefix="a_bot_"  grippername = "gripper" parent = "a_bot_tool0">
    <origin xyz="0.0 0 0.0" rpy="0 0 0"/>
  </xacro:InnerOnlyGripper>
  
  <xacro:include filename="$(find o2as_scene_description)/urdf/robotiq_85_gripper_with_ft300.urdf.xacro" />
  <xacro:robotiq_85_gripper_o2as prefix="b_bot_" parent = "b_bot_ee_link" />
  <xacro:robotiq_85_gripper_o2as prefix="c_bot_" parent = "c_bot_ee_link"/>


  <!-- Add cameras -->
  <link name="b_bot_cam_holder_link" />
  <joint name="b_bot_cam_holder_joint" type="fixed">
    <parent link="b_bot_wrist_2_link" />
    <child link = "b_bot_cam_holder_link" />
    <origin xyz="0.0 -0.06 0.16" rpy="0.0 0.0 ${pi/2}" />
  </joint>

  <xacro:sensor_d435 prefix="b_bot_" parent="b_bot_cam_holder_link">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:sensor_d435>

  <!-- I would like to remove the "world" link definition, but apparently it is necessary for Gazebo -->
  <link name="world" />
  <joint name="world_o2as_joint" type="fixed">
    <parent link="world" />
    <child link="o2as_ground" />
    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
  </joint>
 
</robot>
